### ISSUE TITLE
Loading the GTM Script first

### ISSUE THREAD

**Issue by PomPom248** [nuxt-community/gtm-module#111]
Hello, I'm using this module to load the GTM script and in the app.html I'm loading CookieBots scripts to track the cookies, but in order to track the GTM events I need to place the GTM script before any other script. Do you know how to load this script before the others?
Now the scripts in the app.html are being loaded before the GTM script, which I'm loading using this module.
Thank for your help

**Comment by Scoottykun** [comment]
+1 on this
