### ISSUE TITLE
no gtag config calls were detected

### ISSUE THREAD

**Issue by hoektoe** [nuxt-community/gtm-module#120]
Unsure what to do here, I have setup GA4 and UA via tags to fire on pageviews. Using the https://chrome.google.com/webstore/detail/tag-assistant-for-convers/llpfnmnallbompdmklfkcibfpcfpncdd I get this

![gtm](https://user-images.githubusercontent.com/2276054/115668184-14172a00-a347-11eb-9494-3939da566611.png)

**Comment by henghaxiaoxiong** [comment]
@hoektoe   I also encountered this problem. Has this problem been solved?
