### ISSUE TITLE
Cannot read property 'getElementsByTagName' of null

### ISSUE THREAD

**Issue by mkierdev** [nuxt-community/gtm-module#123]
When module is enabled, it throws error in console:
`Cannot read property 'getElementsByTagName' of null`

It occurs both on 2.3.2 and 2.4.0 version.  What can we do about it?

**Comment by loadkrnis** [comment]
I think your code was executed before HTML elements was drawn.
solution is here.
```javascript
window.onload = function () {
  /* your code here */
}
```

**Comment by mkierdev** [comment]
@loadkrnis yeah, but how it applies to nuxt-gtm situation? I just followed everything from the docs - I put gtm into modules and than, I provided module with my GTM container. Nothing more. I don't even know where would I place your window.onload function

**Comment by loadkrnis** [comment]
@mkierdev Can i see your code all?

**Comment by mkierdev** [comment]
I found a solution - code inside gtm container caused this problem, not the gtm module itself, as I initially thought. 
Thank you for quick response :)
