### ISSUE TITLE
google tag manager multiple ids 

### ISSUE THREAD

**Issue by 1shaked** [nuxt-community/gtm-module#125]
Hey, I am using the google tag manager library, and my SEO team told me they need us (the development team) to implement multiple ids for the google tag manager currently; we know how to implement one `gtm: {
    id: 'GTM-XXXXXXX'
  }`
I will be more than happy if someone can explain how to do that.

**Comment by xseguib** [comment]
There's an issue tagged as question here:

https://github.com/nuxt-community/gtm-module/issues/10
https://github.com/nuxt-community/gtm-module/issues/10#issuecomment-826170924 (solution)

**Comment by 1shaked** [comment]
thx
