### ISSUE TITLE
problem with tracking all visitors

### ISSUE THREAD

**Issue by jakubmagnet** [nuxt-community/gtm-module#126]
Hi,
we have problem with tracking all visitors - site https://www.campus-cowork.com/  - GTM sends to Google Analyticsc only some visits. For example, yesterday from google ads came 27 clicks, but google analytics recorded only 3 users, which is quite a big difference:
![image](https://user-images.githubusercontent.com/88821125/129153735-b66872d3-d8c7-45ee-ada2-1679f6a07376.png)

There is also a huge difference in pageviews - e.g. yesterday it shows me only 29 pageviews, but facebook captured 218 pageviews through its pixel.

GTM settings:
![image](https://user-images.githubusercontent.com/88821125/129153878-f990109c-a705-451d-ac25-fbc54bdc475f.png)

![image](https://user-images.githubusercontent.com/88821125/129153944-b026df9c-abbc-4240-b267-a4be9d8f8052.png)

Do you know, where is the problem?

Thanks for any help.

**Comment by LawlietNick** [comment]
Do you use the same trigger for Facebook Pixel?

And the cookie consent notice at the bottom of the page is preventing tag manager?
I can still use the website without accepting cookies, so there might be an issue there.

Have you implemented Facebook and Hubspot via tag manager or by adding code straight to the site.

**Comment by jakubmagnet** [comment]
Thank you very much! I think you discover problem with cookie notice blocking GTM :). We will try to fix it.

Facebook pixel is implemented through Hubspot and Hubspot is implemented directly in code.
