### ISSUE TITLE
Ignore route option

### ISSUE THREAD

**Issue by mentalrob** [nuxt-community/gtm-module#13]
Hello,
I need to exclude some paths from gtm but can't see an option related to this. I think it's not implemented yet, or if it's implemented can you help me to sort it out ?

**Comment by pi0** [comment]
Hi @mentalrob. You can disable by setting `autoInit` to false in `nuxt.config.js` and use a plugin to manually/conditionally enable GTM:

```js
gtm: {
  autoInit: false
},
plugins: [
  '~/plugins/gtm'
]
```

`plugins/gtm.js`:

```js
const exlucedRoutes = [ '/test' ]
export default function({ $gtm, route }) {
  if (!excludedRoutes.includes(route.path)) {
    $gtm.init() 
 }
}
```

**Comment by mentalrob** [comment]
Thank you for your reply @pi0. I think this will work

**Comment by haliliceylan** [comment]
thanks you very much +111

**Comment by creativefurniture** [comment]
Awesome i was having same issue thanks dude

**Comment by vhoyer** [comment]
> Hi @mentalrob. You can disable by setting `autoInit` to false in `nuxt.config.js` and use a plugin to manually/conditionally enable GTM:
> 
> ```js
> gtm: {
>   autoInit: false
> },
> plugins: [
>   '~/plugins/gtm'
> ]
> ```
> 
> `plugins/gtm.js`:
> 
> ```js
> const exlucedRoutes = [ '/test' ]
> 
> export default function({ $gtm, route }) {
>   if (!excludedRoutes.includes(route.path)) {
>     $gtm.init() 
>  }
> }
> ```

@pi0, but and if the user enters route `/` and then navigates to `/test` with a `nuxt-link`, the plugin would already be loaded, right?

**Comment by kamranata** [comment]
> > Hi @mentalrob. You can disable by setting `autoInit` to false in `nuxt.config.js` and use a plugin to manually/conditionally enable GTM:
> > ```js
> > gtm: {
> >   autoInit: false
> > },
> > plugins: [
> >   '~/plugins/gtm'
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `plugins/gtm.js`:
> > ```js
> > const exlucedRoutes = [ '/test' ]
> > 
> > export default function({ $gtm, route }) {
> >   if (!excludedRoutes.includes(route.path)) {
> >     $gtm.init() 
> >  }
> > }
> > ```
> 
> @pi0, but and if the user enters route `/` and then navigates to `/test` with a `nuxt-link`, the plugin would already be loaded, right?

Did you found solution for this problem?
