### ISSUE TITLE
Error with default options

### ISSUE THREAD

**Issue by SaFrMo** [nuxt-community/gtm-module#22]
I'm running into a `'push' is not a function` error with the default options.

Setting `variables` to `[]` in `nuxt.config.js` fixed the issue for me. Should `variables` be `[]` by default instead of `{}`? Or is this an error with our GTM setup? Thank you!

**Comment by pi0** [comment]
Hi @SaFrMo. It is interesting because  `variables`  has no push operations it will be just meged with other query params. Proabably was just a temporary issue. Otherwise would you please help to reproduce on a simpler project or privately sharing your current project that has error?

**Comment by SaFrMo** [comment]
Hi @pi0 - I'll try to reproduce on a simpler project in the next few days and let you know when that's available. Thanks!

**Comment by SaFrMo** [comment]
@pi0 Turns out the root cause was having webpack 3 and 4 output on the same page - [this](https://github.com/webpack/webpack/issues/6985#issuecomment-464174409) ended up being the fix, and had nothing to do with the gtm-module. Closing the issue - thanks anyway, appreciate your time!
