### ISSUE TITLE
The google tag manager noscript is escaped

### ISSUE THREAD

**Issue by terry-finkel** [nuxt-community/gtm-module#24]
Hi.
When using the noscript option(enabled by default), the google tag manager noscript is added in the document, just after the <body> tag. It looks like this:

`<noscript data-n-head="ssr" data-hid="gtm-noscript" data-pbody-"true">
    "<iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KTVSB4D&a=a&b=b" height="0" width="0" style="display:none;visibility:hidden" title="gtm"></iframe>"
</noscript>`

instead of:

`<noscript data-n-head="ssr" data-hid="gtm-noscript" data-pbody-"true">
    <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KTVSB4D&a=a&b=b" height="0" width="0" style="display:none;visibility:hidden" title="gtm"></iframe>
</noscript>`

Is this normal ? Or is the iframe correctly displayed despite the quotes?

**Comment by pi0** [comment]
Hi @terry-finkel. Yes, it is normal and not a bug. To confirm you can check page source code. `<noscript>` only is effective when browser javascript is disabled.

**Comment by andreasvirkus** [comment]
Even when the JS is disabled, it still gets escaped (with Nuxt 3)

![Screenshot 2022-08-26 at 14 21 50](https://user-images.githubusercontent.com/9140811/186892895-3de9d995-d587-480c-a624-de9bdaf09384.png)
