### ISSUE TITLE
$gtm is undefined

### ISSUE THREAD

**Issue by ThePeach** [nuxt-community/gtm-module#32]
I just moved from the previous google-tag-manager nuxt plugin to this one and stumbled on a significant problem:
In development mode I don't intend to use the gtm plugin, so I load it with a bogus ID (`GTM-XXXXX`). This is causing me a lot of problems in the moment I try to trigger custom events where the plugin breaks the whole application, with the error: 

```
TypeError: "this.$gtm is undefined"
```

is there a solution to this that doesn't mean to fence all calls with a check if `$gtm` is defined?

[edit] this is not happening with the old module

**Comment by VaguelySerious** [comment]
Did you try using the built in option for disabling the plugin in development mode?
```js
// nuxt.config.js
{
  buildModules: [
    '@nuxtjs/gtm',
  ],
  gtm: {
    id: 'GTM-XXXXXXX' // your actual id
    dev: false // << this here
  }
}
```

**Comment by Spice-Z** [comment]
I have same issue.
I tried disabling the plugin in development mode, it doesn't work.

**Comment by Spice-Z** [comment]
Sorry, I can use $gtm to set `gtm.dev = true`.

**Comment by xrei** [comment]
I have same issue with dev set to false

`Cannot read property 'push' of undefined`
logging `this.$gtm` prints `undefined`

**Comment by pi0** [comment]
Hi @ThePeach @xrei . I pushed an update to [v2.3.0](https://github.com/nuxt-community/gtm-module/releases/tag/v2.3.0) with new [enabled](https://github.com/nuxt-community/gtm-module/tree/v2.3.0#enabled) option. Your feedback is more than welcome on this change.

**Comment by proArtex** [comment]
@pi0 thank you so much for this! Console logs are also very useful.

**Comment by francoguilherme** [comment]
@pi0 Should I be setting enabled to true in production mode?

**Comment by marcell17002** [comment]
any update ?
