### ISSUE TITLE
Allow quiet operation in disabled mode

### ISSUE THREAD

**Issue by rchl** [nuxt-community/gtm-module#39]
With ec856996a7caa6f6ef0c21c7c03457ec1a27552c the mocked instance is logging all navigation events. While I appreciate the mocked instance, I don't really want to see the logs in development. Maybe that should be controlled by a new `debug` option?

**Comment by pi0** [comment]
Hi @rchl i can see. Would you be interested in adding option for it? Even disabled by default seems good to me :)

**Comment by rchl** [comment]
I could work on it when I have some time but the more I think about it, the less sure I am how this should be fixed.

So adding `debug` option to log pushes IMO makes sense but then it also makes sense that it works whether using normal or mock variant. So the mock instance would just nothing on calling the methods and there would be separate plugin just for handling logging when `debug` is enabled. Does that sound good to you?
