### ISSUE TITLE
Warning should not be trigged when id is falsy and autoInit is false

### ISSUE THREAD

**Issue by menthol** [nuxt-community/gtm-module#5]
Warning should not be trigged when id is falsy and autoInit is false

linked with #4 

``` js
// Don't include when no GTM id is given
  if (!options.id) {
    // eslint-disable-next-line no-console
    console.warn('[@nuxtjs/gtm] Disabling module because no id is provided!')
    return
  }
```

**Comment by pi0** [comment]
Hi @menthol. Thanks for feedback. In 2.1.x+ you can register multiple ids on runtime by `$gtm.init([id])`. Warning is now only happening if `autoInit` is enabled and no `id` provided. 

https://github.com/nuxt-community/gtm-module/releases/tag/v2.1.0
