### ISSUE TITLE
Convert to runtime module

### ISSUE THREAD

**Issue by SkyaTura** [nuxt-community/gtm-module#55]
The current module mode only runs in build, this forces the ID used in build time, even if you replace on runtime.

In order to allow usage of runtimeConfig (#52), the module should be runtime, as noticed in https://github.com/nuxt-community/gtm-module/pull/53#pullrequestreview-445459552

**Comment by bagaskarala** [comment]
i still cannot use gtm by using runtime config

**Comment by SkyaTura** [comment]
@bagaskarala could you provide more information about your environment? That would help us to understand better your problem.

- Nuxt version
- Module version
- Node version
- A snippet of your config file
