### ISSUE TITLE
How to disable gtm-module?

### ISSUE THREAD

**Issue by Nallelyht** [nuxt-community/gtm-module#65]
Hi!
Can anyone help me?, I need disable gtm in case someone reject analytics cookie, I have autoinit = false and $gtm.init('GTM-XXXXXXX') when accept cookie, but in case of accepting it and then rejecting the cookie :confused: , I try gtm.init(' ') but isnt work.

Thanks in advance! :blush: :blush:

**Comment by pi0** [comment]
Hi @Nallelyht. I'm not sure initializing with a new (or empty) id will disable other injected script. Instead you can full reload webpage (using window.location.reload()) when user rejected after init.
