### ISSUE TITLE
Add Support for GTM Variables with Runtime Config

### ISSUE THREAD

**Issue by tommcclean** [nuxt-community/gtm-module#69]
- Hey, our website compiles Nuxt into a single build artefact which is pushed to many environments (quite a lot of them).
- Each environment has different GTM variables which go into the query string. 
- Using the new runtime config options; I can use a GTM ID configured at runtime; but we would also like to be able to reconfigure the variables at runtime too.
- It looks like this is compile time only at the moment: https://github.com/nuxt-community/gtm-module/blob/master/lib/module.js#L65

I intended to contribute a fix, but I am not sure how to move these options over to runtime config unfortunately, is this something support could be added for?

This is essentially what we want to achieve
![image](https://user-images.githubusercontent.com/10741583/92401412-7fe4b380-f125-11ea-908e-5fb8657d7e7f.png)

**Comment by pi0** [comment]
https://github.com/nuxt-community/gtm-module/releases/tag/v2.4.0
