### ISSUE TITLE
Unable to configure PublicRuntimeConfiguration per readme

### ISSUE THREAD

**Issue by tommcclean** [nuxt-community/gtm-module#70]
**Reproduction**: https://github.com/tommcclean/nuxtgtmruntime/blob/master/nuxt.config.js#L56
- The reproduction is a new vanilla Nuxt site using >2.14, only modifications are installing this module and updating the config.

**Expectation**
- When running the website with either `yarn dev` or `yarn build` + `yarn start`
- GTM would request the XHR: `https://www.googletagmanager.com/gtm.js?id=GTM-123456` using the publicRuntimeConfig override

**Actual**
- GTM uses the default and requests `https://www.googletagmanager.com/gtm.js?id=GTM-XXXXXXX`

**NB**
- When I log out the GTM object from runtimeConfig, I can see it is evaluated in runtime; it just doesn't update the module settings.
- It also doesn't look like it has been developed yet to support variables; which is in our use case

**Comment by tommcclean** [comment]
Hmm, thinking maybe it might not be published actually; the readme in this repo isn't the same version as the one on NPM

**Comment by tommcclean** [comment]
^ Thats the badger, hasn't been published since July

**Comment by raphaelarias** [comment]
Yep, still hasn't been updated.

**Comment by tommcclean** [comment]
Yeah I am not sure if this repo is maintained; I tried to reach out to get a publish but couldn't get a reply.

For me I ended up writing my own plugin which initialises GTM, as that gets done at runtime and can support the other variables being dynamic too

**Comment by pi0** [comment]
Hi. Sorry i kinda lost track of this module a while. Feature released: https://github.com/nuxt-community/gtm-module/releases/tag/v2.4.0
