### ISSUE TITLE
create gtm Duplicate 

### ISSUE THREAD

**Issue by liseipi** [nuxt-community/gtm-module#77]
Click on new page, create gtm Duplicate 
![image](https://user-images.githubusercontent.com/11224366/93289016-d631b080-f80f-11ea-9f1f-522a59805c6b.png)

**Comment by petermucha** [comment]
We have the same issue. 

Did you disable auto init in `nuxt.config.ts`?
`export default {
  gtm: {
    autoInit: false
  }
}`

**Comment by yf-hk** [comment]
> We have the same issue.
> 
> Did you disable auto init in `nuxt.config.ts`? `export default { gtm: { autoInit: false } }`

What does `autoInit: false` do? It seems that after adding it, I can't see any GTM events.

**Comment by yf-hk** [comment]
Why it's closed? I still can't solve thi problem

**Comment by liseipi** [comment]
> Why it's closed? I still can't solve thi problem

### has been successful, this is my code configuration

```
gtm: {
    enabled: true,
    // debug: true,

    id: process.env.GTM_ID,
    layer: 'dataLayer',
    variables: { sites: 'www' },

    // pageTracking: true,
    pageViewEventName: 'nuxtRoute',   // nuxtRoute and pageViewEventName

    // autoInit: true,

    scriptId: 'gtm-script',
    scriptDefer: true,
    scriptURL: 'https://www.googletagmanager.com/gtm.js',
    crossOrigin: false,

    noscript: true,
    noscriptId: 'gtm-noscript',
    noscriptURL: 'https://www.googletagmanager.com/ns.html'
  },
```
