### ISSUE TITLE
Console logging still occurring with debug set to false

### ISSUE THREAD

**Issue by philiplindberg** [nuxt-community/gtm-module#79]
It seems like console logging is still occurring even though I have `debug` set to `false` (which is the default value). An easy way to reproduce the issue is to enable `pageTracking` - this will log `GTM` messages in the console even though `debug` disabled.

**Comment by hacknug** [comment]
@philiplindberg can you confirm this is still an issue? I have a couple projects with `{ debug: false, pageTracking: true }` and I don't see any logs on the console.

**Comment by philiplindberg** [comment]
Looks like this is no longer an issue with the latest version (2.4.0). Great!
