### ISSUE TITLE
Use different container ID for different tlds 

### ISSUE THREAD

**Issue by aboullait** [nuxt-community/gtm-module#9]
Hello, First thanks for this new module.
I need your help to implement the module inside a multiTlds structure. 
For example i have 4 tlds example.fr, example.be, example.mc and example.ma
I'm using nuxt-i18n to handle translations for these domains. i cand find where can i configure gtm-module to handle my 4 domains.
If it's possible to define the container ID (gtm id) in an external file and import it on page reload it will resolve my problem.

**Comment by pi0** [comment]
Hi @aboullait. You can`autoInit` to false in `nuxt.config.js` and don't add any id there and use a plugin to select GTM based on domain.

`nuxt.config.js`:

```js
gtm: {
  autoInit: false
},
plugins: [
  '~/plugins/gtm'
]
```

`plugins/gtm.js`:

```js
function getHost(req) {
  if (req && req.host) {
     return req.host
  }

  if (typeof window !== 'undefined') {
   return window.location.host
 }
}

export default function({ $gtm, req }) {
  const host = getHost(req)
  const gtmId = getGTMId(host) // TODO
  if (gtmId) {
   $gtm.init(gtmId)
  }
}
```
